import React, { useState, useCallback, useRef, useEffect } from 'react';
import { 
  ReactFlow, 
  MiniMap, 
  Controls, 
  Background, 
  useNodesState, 
  useEdgesState, 
  addEdge,
  ReactFlowProvider,
  Connection,
  applyNodeChanges,
  applyEdgeChanges,
  NodeChange,
  EdgeChange,
  Node,
  Edge
} from '@xyflow/react';
import '@xyflow/react/dist/style.css';
import { Workflow, AutomationsNode } from './types';
import { NodeLibrary } from './NodeLibrary';
import { NodeConfigPanel } from './NodeConfigPanel';
import { AIPromptBar } from './AIPromptBar';
import { X, Play, Save, History, MousePointer2, ChevronDown, Trash2 } from 'lucide-react';
import { CustomNode } from './nodes/CustomNode';
import { supabase } from '../supabaseClient';
import toast from 'react-hot-toast';

const nodeTypes = {
  customNode: CustomNode,
};

function FlowCanvas({ initialWorkflow, onBack }: { initialWorkflow: Workflow | null, onBack: () => void }) {
  const [nodes, setNodes] = useNodesState(initialWorkflow?.nodes || []);
  const [edges, setEdges] = useEdgesState(initialWorkflow?.edges || []);
  const [workflowName, setWorkflowName] = useState(initialWorkflow?.name || 'Untitled Workflow');
  const [isActive, setIsActive] = useState(initialWorkflow?.is_active || false);
  const [selectedNode, setSelectedNode] = useState<AutomationsNode | null>(null);
  const [showLogView, setShowLogView] = useState(false);

  const onNodesChange = useCallback((changes: NodeChange[]) => setNodes((nds) => applyNodeChanges(changes, nds) as AutomationsNode[]), [setNodes]);
  const onEdgesChange = useCallback((changes: EdgeChange[]) => setEdges((eds) => applyEdgeChanges(changes, eds)), [setEdges]);
  const onConnect = useCallback((connection: Connection) => setEdges((eds) => addEdge({ ...connection, animated: true, style: { stroke: '#22c55e', strokeWidth: 2 } }, eds)), [setEdges]);

  const onDragOver = useCallback((event: React.DragEvent) => {
    event.preventDefault();
    event.dataTransfer.dropEffect = 'move';
  }, []);

  const onDrop = useCallback((event: React.DragEvent) => {
    event.preventDefault();
    const type = event.dataTransfer.getData('application/reactflow/type');
    const label = event.dataTransfer.getData('application/reactflow/label');
    const category = event.dataTransfer.getData('application/reactflow/category');
    const icon = event.dataTransfer.getData('application/reactflow/icon');
    const description = event.dataTransfer.getData('application/reactflow/description');
    const subtype = event.dataTransfer.getData('application/reactflow/subtype');

    if (!type || !label) return;

    const position = {
      x: event.clientX - 300, 
      y: event.clientY - 200,
    };

    const newNode: AutomationsNode = {
      id: `${subtype}-${Date.now()}`,
      type: 'customNode',
      position,
      data: {
        type: type as any,
        label,
        category,
        icon,
        description,
        subtype,
        config: {}
      },
    };

    setNodes((nds) => nds.concat(newNode));
  }, [setNodes]);

  const onNodeClick = (event: React.MouseEvent, node: Node) => {
    setSelectedNode(node as AutomationsNode);
  };
  
  const handleAIGenerated = (data: any) => {
    // Generate nodes and animate them
    if (data.nodes) {
       setWorkflowName(data.workflow_name || 'AI Generated Workflow');
       setNodes([]);
       setEdges([]);
       
       let delay = 0;
       
       data.nodes.forEach((n: any) => {
         setTimeout(() => {
           setNodes(nds => [...nds, {
             id: n.id,
             type: 'customNode',
             position: n.position,
             data: {
                type: n.type,
                subtype: n.subtype,
                label: n.label,
                category: n.type.toUpperCase(),
                icon: n.icon,
                description: 'Generated by AI',
                config: n.config
             }
           } as AutomationsNode]);
         }, delay);
         delay += 300;
       });
       
       setTimeout(() => {
         if (data.edges) {
            setEdges(data.edges.map((e: any) => ({
              ...e,
              style: { stroke: '#22c55e', strokeWidth: 2 },
              animated: true
            })));
         }
         toast.success(`Created: ${data.nodes.length} nodes, ${data.edges?.length || 0} connections`);
       }, delay + 200);
    }
  };

  const handleUpdateNodeConfig = (nodeId: string, newConfig: any) => {
    setNodes((nds) =>
      nds.map((n) => {
        if (n.id === nodeId) {
          n.data = { ...n.data, config: newConfig };
        }
        return n;
      })
    );
    setSelectedNode((prev) => {
       if (prev && prev.id === nodeId) {
          return { ...prev, data: { ...prev.data, config: newConfig } };
       }
       return prev;
    });
  };

  const handleDeleteNode = (nodeId: string) => {
    setNodes(nds => nds.filter(n => n.id !== nodeId));
    setEdges(eds => eds.filter(e => e.source !== nodeId && e.target !== nodeId));
    setSelectedNode(null);
  };

  const handleSave = async () => {
    const payload = {
      name: workflowName,
      nodes,
      edges,
      is_active: isActive,
      trigger_type: nodes.find(n => n.data.type === 'trigger')?.data.subtype || 'Unknown',
    };

    try {
      if (initialWorkflow?.id) {
         await supabase.from('workflows').update(payload).eq('id', initialWorkflow.id);
      } else {
         await supabase.from('workflows').insert([payload]);
      }
      toast.success('Workflow saved');
    } catch (e: any) {
      toast.error('Error saving workflow.');
    }
  };

  return (
    <div className="flex w-full h-full bg-gray-50 text-gray-900 overflow-hidden">
      <NodeLibrary />

      <div className="flex-1 flex flex-col relative" onDrop={onDrop} onDragOver={onDragOver}>
        <div className="bg-white border-b border-gray-200 flex items-center justify-between px-4 py-3 z-20">
          <div className="flex items-center gap-4">
             <button onClick={onBack} className="p-2 hover:bg-gray-100 rounded-lg transition-colors text-gray-500 hover:text-gray-900">
                <X size={20} />
             </button>
             <input 
               type="text" 
               value={workflowName} 
               onChange={e => setWorkflowName(e.target.value)}
               className="text-lg font-black text-gray-900 bg-transparent border-none focus:ring-0 w-64 px-2 py-1 rounded-md hover:bg-gray-100 transition-colors cursor-text"
               placeholder="Workflow Name"
             />
             <div className="h-6 w-px bg-gray-200 mx-2" />
             <label className="flex items-center gap-2 cursor-pointer">
               <div className={`w-10 h-5 rounded-full p-0.5 transition-colors ${isActive ? 'bg-blue-600' : 'bg-gray-300'}`}>
                 <div className={`w-4 h-4 bg-white rounded-full shadow-sm transition-transform ${isActive ? 'translate-x-5' : 'translate-x-0'}`} />
               </div>
               <span className="text-[10px] font-black uppercase tracking-widest text-gray-500">{isActive ? 'ACTIVE' : 'PAUSED'}</span>
             </label>
          </div>
          <div className="flex items-center gap-3">
             <button className="flex items-center gap-2 px-3 py-1.5 bg-gray-100 text-gray-600 rounded-lg text-xs font-bold transition-colors hover:text-gray-900">
                History <ChevronDown size={14}/>
             </button>
             <button className="flex items-center gap-2 px-3 py-1.5 bg-gray-100 text-gray-600 rounded-lg text-xs font-bold transition-colors hover:text-gray-900">
                🐛 Debug
             </button>
             <button onClick={handleSave} className="flex items-center gap-1.5 px-4 py-2 bg-blue-600 text-white rounded-xl text-xs font-black uppercase tracking-widest shadow-sm shadow-blue-500/20 hover:bg-blue-700 transition-colors">
               <Save size={14} /> Save
             </button>
          </div>
        </div>

        <AIPromptBar onGenerated={handleAIGenerated} />

        <div className="flex-1 relative w-full h-full">
          <ReactFlow
            nodes={nodes}
            edges={edges}
            onNodesChange={onNodesChange}
            onEdgesChange={onEdgesChange}
            onConnect={onConnect}
            onNodeClick={onNodeClick}
            onPaneClick={() => setSelectedNode(null)}
            nodeTypes={nodeTypes}
            fitView
            defaultEdgeOptions={{ animated: true, style: { strokeDasharray: 5, strokeWidth: 2, stroke: '#22c55e' } }}
          >
            <Background color="rgba(0,0,0,0.05)" size={2} gap={20} />
            <Controls className="bg-white border-gray-200 shadow-xl rounded-xl overflow-hidden fill-gray-500 top-4 left-4 absolute" />
            <MiniMap 
              className="bg-white rounded-xl border border-gray-200 overflow-hidden" 
              maskColor="rgba(249, 250, 251, 0.8)" 
              nodeColor="#3b82f6"
            />
          </ReactFlow>

          {/* Execution Log Toggle */}
          <div className="absolute bottom-4 left-1/2 -translate-x-1/2 z-50">
             <button 
               onClick={() => setShowLogView(!showLogView)}
               className="bg-white border border-gray-300 text-gray-900 px-6 py-2 rounded-full shadow-lg flex items-center gap-2 text-sm font-bold uppercase tracking-widest hover:bg-gray-50 transition-colors"
             >
                <History size={16} className="text-blue-500" /> 
                {showLogView ? 'Hide Execution Log' : 'Show Execution Log'}
             </button>
          </div>

          {/* Execution Log Panel */}
          {showLogView && (
            <div className="absolute bottom-16 left-1/2 -translate-x-1/2 w-[600px] max-h-64 bg-gray-50 border border-gray-300 rounded-xl shadow-2xl z-40 overflow-hidden flex flex-col font-mono text-xs">
              <div className="bg-white border-b border-gray-300 p-2 px-4 flex justify-between items-center text-gray-500 font-bold uppercase tracking-widest">
                 <span>▼ Execution Log</span>
                 <button className="hover:text-gray-900">Clear</button>
              </div>
              <div className="p-4 overflow-y-auto space-y-2 text-gray-600">
                <div className="flex gap-4"><span>10:23:01</span><span className="text-green-500">✅</span><span>Trigger fired: New Property</span></div>
                <div className="flex gap-4"><span>10:23:02</span><span className="text-green-500">✅</span><span>Gemini caption generated</span></div>
                <div className="flex gap-4"><span>10:23:02</span><span className="text-green-500">✅</span><span>Facebook post opened</span></div>
                <div className="flex gap-4"><span>10:23:03</span><span className="text-yellow-500">⚠️</span><span>Instagram: caption copied</span></div>
                <div className="flex gap-4"><span>10:23:03</span><span className="text-green-500">✅</span><span>Email sent to 24 subscribers</span></div>
                <div className="mt-4 pt-4 border-t border-gray-200 text-gray-500">
                   Duration: 2.3s | Status: ✅ Success
                </div>
              </div>
            </div>
          )}
        </div>
      </div>

      {selectedNode && (
        <NodeConfigPanel 
          node={selectedNode} 
          onClose={() => setSelectedNode(null)} 
          onUpdate={handleUpdateNodeConfig} 
          onDelete={handleDeleteNode}
        />
      )}
    </div>
  );
}

export function WorkflowCanvas(props: any) {
   return (
     <ReactFlowProvider>
       <FlowCanvas {...props} />
     </ReactFlowProvider>
   );
}
