-- 1. Create the admin_users table if it doesn't exist
CREATE TABLE IF NOT EXISTS public.admin_users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email TEXT UNIQUE NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Add some specific admins
-- Note: These users must also be created in Supabase Auth via the dashboard or signUp
INSERT INTO public.admin_users (email) VALUES ('abhishekdewminaa@gmail.com') ON CONFLICT (email) DO NOTHING;
INSERT INTO public.admin_users (email) VALUES ('ceo.lankaland@gmail.com') ON CONFLICT (email) DO NOTHING;

-- 3. In order to allow admins to edit any property, we need an RLS policy on the properties table.
-- Enable RLS on properties if not already enabled.
ALTER TABLE public.properties ENABLE ROW LEVEL SECURITY;

-- 4. Create the update policy
-- Drop existing update policy if you want to replace it
-- DROP POLICY IF EXISTS "Enable update for admins" ON public.properties;

CREATE POLICY "Enable update for users and admins"
ON public.properties
FOR UPDATE
USING (
  -- Either the user matches the agent_id (or published_by) OR the user is in admin_users
  auth.email() = agent_id 
  OR published_by = 'admin'
  OR EXISTS (
    SELECT 1 FROM public.admin_users WHERE email = auth.email()
  )
)
WITH CHECK (
  auth.email() = agent_id 
  OR published_by = 'admin'
  OR EXISTS (
    SELECT 1 FROM public.admin_users WHERE email = auth.email()
  )
);

-- Additionally, allow DELETE
-- DROP POLICY IF EXISTS "Enable delete for admins" ON public.properties;
CREATE POLICY "Enable delete for admins"
ON public.properties
FOR DELETE
USING (
  auth.email() = agent_id 
  OR EXISTS (
    SELECT 1 FROM public.admin_users WHERE email = auth.email()
  )
);
