/// <reference types="vite/client" />
import { createClient } from '@supabase/supabase-js'

const SUPABASE_URL = 
  import.meta.env.VITE_SUPABASE_URL?.
    replace(/\/rest\/v1\/?$/, '').
    replace(/\/$/, '') ||
  "https://qsqqolvsndvkwegvcfqv.supabase.co"

const SUPABASE_KEY =
  import.meta.env.VITE_SUPABASE_ANON_KEY ||
  "sb_publishable_srMG0yYK9V0lH1ipf9C4Hw_ae0_eCe5"

export const supabase = createClient(
  SUPABASE_URL,
  SUPABASE_KEY,
  {
    global: {
      fetch: (...args) => 
        globalThis.fetch(...(args as [RequestInfo | URL, RequestInit | undefined]))
    },
    auth: {
      persistSession: true,
      autoRefreshToken: true,
      detectSessionInUrl: false
    }
  }
)

/**
 * Expected Supabase Schema for 'properties' table:
 * 
 * CREATE TABLE properties (
 *   id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 *   title TEXT NOT NULL,
 *   price TEXT,
 *   district TEXT,
 *   city TEXT,
 *   property_type TEXT,
 *   listing_type TEXT,
 *   land_area TEXT,
 *   floor_area TEXT,
 *   floors TEXT,
 *   rooms TEXT,
 *   bathrooms TEXT,
 *   description TEXT,
 *   is_negotiable BOOLEAN,
 *   images TEXT[], 
 *   package_tier TEXT,
 *   agent_id TEXT,
 *   created_at TIMESTAMPTZ DEFAULT NOW(),
 *   location TEXT,
 *   lat FLOAT8,
 *   lng FLOAT8,
 *   additional_info JSONB,
 *   location_link TEXT
 * );
 */
