/// <reference types="vite/client" />
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://qsqqolvsndvkwegvcfqv.supabase.co";
const SUPABASE_PUBLIC_KEY = "sb_publishable_srMG0yYK9V0lH1ipf9C4Hw_ae0_eCe5";

/**
 * Configure Supabase Client
 * 
 * FIX for "Uncaught TypeError: Cannot set property fetch of #<Window> which has only a getter"
 * We explicitly pass the browser's fetch to avoid polyfill attempts.
 */
export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLIC_KEY, {
  auth: {
    persistSession: true,
    autoRefreshToken: true,
  },
  global: {
    fetch: (input, init) => fetch(input, init),
  },
});

/**
 * Expected Supabase Schema for 'properties' table:
 * 
 * CREATE TABLE properties (
 *   id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 *   title TEXT NOT NULL,
 *   price TEXT,
 *   district TEXT,
 *   city TEXT,
 *   property_type TEXT,
 *   listing_type TEXT,
 *   land_area TEXT,
 *   floor_area TEXT,
 *   floors TEXT,
 *   rooms TEXT,
 *   bathrooms TEXT,
 *   description TEXT,
 *   is_negotiable BOOLEAN,
 *   images TEXT[], 
 *   package_tier TEXT,
 *   agent_id TEXT,
 *   created_at TIMESTAMPTZ DEFAULT NOW(),
 *   location TEXT,
 *   lat FLOAT8,
 *   lng FLOAT8,
 *   additional_info JSONB,
 *   location_link TEXT
 * );
 */
